name: NodeJS Weather App
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm install